### PR TITLE
Accepted multiple pull requests, fixed an issue

### PR DESCRIPTION
**Pull request by gjuchault**
Please consider it. This does makes a lot of improvements.

Pull requests :
https://github.com/jeresig/i18n-node-2/pull/57
https://github.com/jeresig/i18n-node-2/pull/56
https://github.com/jeresig/i18n-node-2/pull/52
https://github.com/jeresig/i18n-node-2/pull/51
https://github.com/jeresig/i18n-node-2/pull/48
https://github.com/jeresig/i18n-node-2/pull/45
https://github.com/jeresig/i18n-node-2/pull/40
https://github.com/jeresig/i18n-node-2/pull/36
https://github.com/jeresig/i18n-node-2/pull/32
https://github.com/jeresig/i18n-node-2/pull/31

Issues :
https://github.com/jeresig/i18n-node-2/issues/50
https://github.com/jeresig/i18n-node-2/issues/44

### CODE REVIEW

**Comment by jeresig** [comment]
Awesome, thank you so much for your help! I've just merged this and have made you a committer. I haven't had a chance to work on this recently so please feel free to make any fixes or improvements that you want!

**Comment by jeresig** [comment]
Oh - and let me know when you want to kick off a new release on npm and I can make that happen, or give me your npm username and I can give you access there, as well.

**Comment by KLicheR** [comment]
Hi!,
A new release on npm would be very nice!
I would also be happy to help if you want.
My npm username: klicher

**Comment by jeresig** [comment]
@KLicheR Great! I just added you as a contributor here on Github and on NPM as well! Thank you for your help.

**Comment by KLicheR** [comment]
Thanks!
I'll Make a new release with all the pull requests and I will check for fixing the remaining issues after that.

**Pull request merged**
