### PR TITLE
support setLocaleFromEnvironmentVariable()

### PR DESCRIPTION
**Pull request by shibukawa**

### CODE REVIEW

**Comment by gjuchault** [comment]
Okay, thanks for your pull request, seems interesting. Could you also push semver version and update readme as well ?
Thanks again :)

**Comment by shibukawa** [comment]
Thank you. I want to use this module with Electron. This method is designed for this purpose.

Which version do you like? 0.5.1 or 0.6.0.

**Comment by gjuchault** [comment]
Well, it's not a patch; it's a minor update, so 0.6.0

**Comment by shibukawa** [comment]
Fixed!

**Comment by gjuchault** [comment]
Thank you very much for your time :)

**Pull request merged**
