### PR TITLE
Base files for locales

### PR DESCRIPTION
**Pull request by awilczek**

### CODE REVIEW

**Comment by awilczek** [comment]
I now think the RegExp is too limiting. Param `bases` should be rather a custom function. It should give more freedom to the user and simplify this PR.

**Comment by gjuchault** [comment]
As this is a big update, I prefer to wait for @jeresig to validate this, but this looks nice (I do prefer a lot functions instead of regexps -- perf).

**Comment by pawelrychlik** [comment]
:+1:

**Comment by awilczek** [comment]
I wonder yet about adding some caching here.

**Comment by jeresig** [comment]
Looks good to me! Thanks for tackling this :)

**Comment by awilczek** [comment]
When can I expect the publishing? :)
I'd put the cashing in other version because it's not gonna be super easy.

**Comment by gjuchault** [comment]
Well this has been merged

**Pull request merged**
